### transfer money
POST http://localhost:9000/transfer/{{$random.uuid}}
Content-Type: application/json

{
  "amount": 500,
  "from": "001",
  "to": "002"
}

### transfer status
GET http://localhost:9000/transfer/7a642a9a-4179-45ed-9cd4-1d6cdf18b523
Content-Type: application/json
